adds env var check to ci/cd pipeline

diff --git a/.github/workflows/docker-pipeline.yml b/.github/workflows/docker-pipeline.yml
--- a/.github/workflows/docker-pipeline.yml
+++ b/.github/workflows/docker-pipeline.yml
@@ -11,6 +11,11 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Verify Env
+        run: |
+          ls -la .env
+          grep "GOOGLE_PROJECT_ID" .env || echo "MISSING PROJECT ID"
+
       - name: Build and Deploy
         run: |
           ln -sf /home/jawadazeem/billing/.env .env
